var:
  debug: false
  commandsonlyfromconsole: false
save:
  interval: 900
  broadcast: true
  disablestructuresaving: false
  onplugindisable: true
backup:
  enabled: false
  interval: 21600
  broadcast: true
  savebefore: true
  rateLimit: -1
  localfs:
    enabled: true
    destinationfolders: []
    worlds:
      - world
    MaxNumberOfWorldsBackups: 2
    pluginsfolder: true
    MaxNumberOfPluginsBackups: 2
    otherfolders: []
    MaxNumberOfOtherFoldersBackups: 2
    excludefolders: []
    zip: true
restart:
  juststop: false
  oncrash:
    enabled: false
    scriptpath: ''
    timeout: 60
    checkerstartdelay: 20
    runonnonpluginstop: false
  auto:
    enabled: false
    broadcast: true
    scriptpath: ''
    time: []
    countdown:
      enabled: true
      broadcastonsecond:
        - 60
        - 30
        - 10
        - 9
        - 8
        - 7
        - 6
        - 5
        - 4
        - 3
        - 2
        - 1
    commands: []
consolecommand:
  timemode:
    enabled: false
    times: {}
  intervalmode:
    enabled: false
    intervals: {}
networkwatcher:
  mainthreadnetaccess:
    warn: true
    interrupt: false
